name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Java 21 for Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Build WAR
      - name: Build with Maven
        run: mvn -B clean package

      # 4. Copy WAR to EC2's Tomcat
      - name: Copy WAR to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key:   ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.war"
          target: "/var/lib/tomcat10/webapps/" 

      # 5. Restart Tomcat so the new WAR is deployed
      - name: Restart Tomcat
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key:   ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart tomcat10

